[tool.towncrier]
package = "outcome"
filename = "docs/source/history.rst"
directory = "newsfragments"
underlines = ["-", "~", "^"]
issue_format = "`#{issue} <https://github.com/python-trio/outcome/issues/{issue}>`__"

[tool.isort]
combine_as_imports = true
profile = "black"
skip_gitignore = true

[tool.mypy]
# Be strict about use of Mypy
strict = true
warn_unused_ignores = true
warn_unused_configs = true
warn_redundant_casts = true
warn_return_any = true

# Avoid subtle backsliding
disallow_incomplete_defs = true
disallow_subclassing_any = true

# Enable gradually / for new modules
check_untyped_defs = false
disallow_untyped_calls = false
disallow_untyped_defs = false

# DO NOT use `ignore_errors`; it doesn't apply
# downstream and users have to deal with them.
