[tool.towncrier]
package = "outcome"
filename = "docs/source/history.rst"
directory = "newsfragments"
underlines = ["-", "~", "^"]
issue_format = "`#{issue} <https://github.com/python-trio/outcome/issues/{issue}>`__"

[tool.isort]
combine_as_imports = true
profile = "black"
skip_gitignore = true
